name: doorcareworker
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  equatable: ^2.0.5
  pinput: ^5.0.0
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.1.2
  lottie: ^3.1.2
  dio: ^5.4.3+1
  onboarding: ^4.0.2
  shared_preferences: ^2.2.3
  toastification: ^2.0.0
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  flutter_secure_storage: ^9.2.2
  intl: ^0.19.0
  geocoding: ^3.0.0
  flutter_iconly: ^1.0.2
  google_maps_flutter: ^2.9.0
  location: ^7.0.0
  flutter_polyline_points: ^2.1.0
  flutter_dotenv: ^5.1.0
  google_fonts: ^6.2.1
  socket_io_client: ^2.0.3+1
  http: ^1.2.2
  time_picker_spinner_pop_up: ^2.0.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/png/app_logo.png"  # Path to your app icon image
  adaptive_icon_background: "#6759FF"  # Background color for the adaptive icon
  adaptive_icon_foreground: "assets/png/app_logo_foreground.png"  # Foreground image for the adaptive icon

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/png/
    - assets/svg/
    - assets/jason/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
