// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQCpevB5M8LnFfccqyxW7KfGJoOkskRAE',
    appId: '1:2219531149:web:a3f96789a7be80b4fafbc4',
    messagingSenderId: '2219531149',
    projectId: 'doorcareworker',
    authDomain: 'doorcareworker.firebaseapp.com',
    storageBucket: 'doorcareworker.appspot.com',
    measurementId: 'G-T157YCB4HL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcXiOxDH1yHTHRTvWo-f25rOQ_gJ_YxEk',
    appId: '1:2219531149:android:e61341176efe8e5ffafbc4',
    messagingSenderId: '2219531149',
    projectId: 'doorcareworker',
    storageBucket: 'doorcareworker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnqYYYvMuql4-4WWvdhwXTAvmnqRk3Aos',
    appId: '1:2219531149:ios:b4cb448961958b73fafbc4',
    messagingSenderId: '2219531149',
    projectId: 'doorcareworker',
    storageBucket: 'doorcareworker.appspot.com',
    iosBundleId: 'com.example.doorCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnqYYYvMuql4-4WWvdhwXTAvmnqRk3Aos',
    appId: '1:2219531149:ios:b4cb448961958b73fafbc4',
    messagingSenderId: '2219531149',
    projectId: 'doorcareworker',
    storageBucket: 'doorcareworker.appspot.com',
    iosBundleId: 'com.example.doorCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQCpevB5M8LnFfccqyxW7KfGJoOkskRAE',
    appId: '1:2219531149:web:6e09789c23a3e271fafbc4',
    messagingSenderId: '2219531149',
    projectId: 'doorcareworker',
    authDomain: 'doorcareworker.firebaseapp.com',
    storageBucket: 'doorcareworker.appspot.com',
    measurementId: 'G-74BYG0CYRB',
  );
}
