// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPrA_IcVaxixeb0rtndGopZvDF_7Nppio',
    appId: '1:608377486262:web:0a7910ee31680089d7df17',
    messagingSenderId: '608377486262',
    projectId: 'doorcareworker-23af7',
    authDomain: 'doorcareworker-23af7.firebaseapp.com',
    storageBucket: 'doorcareworker-23af7.appspot.com',
    measurementId: 'G-3XP44FPEBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy2CN3fZNZp4dF-L5jllAvspxDXINv1wQ',
    appId: '1:608377486262:android:b675280230ee8a87d7df17',
    messagingSenderId: '608377486262',
    projectId: 'doorcareworker-23af7',
    storageBucket: 'doorcareworker-23af7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsHC07AOmxn5JGzELTDwFHD5WPFIufL0I',
    appId: '1:608377486262:ios:9ac5aae7560a4f90d7df17',
    messagingSenderId: '608377486262',
    projectId: 'doorcareworker-23af7',
    storageBucket: 'doorcareworker-23af7.appspot.com',
    iosBundleId: 'com.example.doorCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsHC07AOmxn5JGzELTDwFHD5WPFIufL0I',
    appId: '1:608377486262:ios:9ac5aae7560a4f90d7df17',
    messagingSenderId: '608377486262',
    projectId: 'doorcareworker-23af7',
    storageBucket: 'doorcareworker-23af7.appspot.com',
    iosBundleId: 'com.example.doorCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPrA_IcVaxixeb0rtndGopZvDF_7Nppio',
    appId: '1:608377486262:web:b254f5e0d3f3426ed7df17',
    messagingSenderId: '608377486262',
    projectId: 'doorcareworker-23af7',
    authDomain: 'doorcareworker-23af7.firebaseapp.com',
    storageBucket: 'doorcareworker-23af7.appspot.com',
    measurementId: 'G-FSS37CHJ4L',
  );
}
